//notes getList
export const GET_NOTES_REQ = "GET_NOTES_REQ";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";

//post notes
export const CREATE_NOTE_REQ="CREATE_NOTE_REQ";
export const CREATE_NOTE_SUCCESS="CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAILURE="CREATE_NOTE_FAILURE";

//update notes
export const UPDATE_NOTE_REQ="UPDATE_NOTE_REQ";
export const UPDATE_NOTE_SUCCESS="UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILURE="UPDATE_NOTE_FAILURE";

//Delete notes
export const DELETE_NOTES_REQ="DELETE_NOTES_REQ";
export const DELETE_NOTES_SUCCESS="DELETE_NOTES_SUCCESS";
export const DELETE_NOTES_FAILURE="DELETE_NOTES_FAILURE";
