//login
export const USER_LOGIN_REQ = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE="USER_LOGIN_FAILURE";
export const USER_LOG_OUT = "USER_LOG_OUT";

//register
export const USER_REGISTER_REQ = "USER_REGISTER_REQ";
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE="USER_REGISTER_FAILURE";

//profile update
export const USER_UPDATE_REQ = "USER_UPDATE_REQ";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";